import {env} from 'cloudflare:workers';
import {z} from 'zod';
import {initialContent,Content} from './data';
type Runtime = {DB?:D1Database;BUCKET?:R2Bucket;ADMIN_INITIAL_HASH?:string;ADMIN_INITIAL_SALT?:string};
export const runtime=env as Runtime;
export function db(){if(!runtime.DB)throw new Error('Almacenamiento no disponible');return runtime.DB;}
export function json(value:unknown,status=200,headers:Record<string,string>={}){return Response.json(value,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...headers}})}
export function sameOrigin(request:Request){const origin=request.headers.get('origin');return !!origin&&origin===new URL(request.url).origin;}
export function fail(error:unknown){console.error('Medicalshop request failed',error instanceof Error?error.message:'unknown');return json({error:'No se pudo completar la operación. Inténtalo nuevamente.'},503)}
export async function body(request:Request,max=1_000_000){if(Number(request.headers.get('content-length'))>max)throw Error('Payload too large');const data=await request.text();if(data.length>max)throw Error('Payload too large');return JSON.parse(data)}
const text=z.string().max(5000);const image=z.string().max(2048).refine(s=>/^\/assets\/[\w./-]+$/.test(s)||/^\/api\/media\/[a-f0-9-]+\.(png|jpg|webp)$/.test(s)||/^https:\/\//.test(s),'Usa una imagen cargada o una URL https.');
const crop=z.array(z.number().finite().min(0).max(20000)).min(4).max(6).refine(c=>c[2]>0&&c[3]>0).optional();
const id=z.string().regex(/^[a-zA-Z0-9_-]{1,100}$/);
const categorySchema=z.object({id,name:z.string().trim().min(1).max(150),title:z.string().trim().min(1).max(200),description:text,image,crop});
const productSchema=z.object({id,name:z.string().trim().min(1).max(150),category:id,description:text,price:z.number().finite().min(0).max(10000000).nullable(),image,crop,sizes:z.string().max(300),colors:z.string().max(300),stock:z.enum(['Disponible','Consultar','Agotado']),featured:z.boolean(),visible:z.boolean()});
export const contentSchema=z.object({settings:z.record(text),categories:z.array(categorySchema).min(1).max(100),products:z.array(productSchema).max(2000)}).superRefine((v,ctx)=>{const ids=new Set(v.categories.map(c=>c.id));if(ids.size!==v.categories.length||new Set(v.products.map(p=>p.id)).size!==v.products.length)ctx.addIssue({code:'custom',message:'Los identificadores deben ser únicos.'});if(v.products.some(p=>!ids.has(p.category)))ctx.addIssue({code:'custom',message:'Todos los productos necesitan una categoría existente.'});for(const k of Object.keys(initialContent.settings)){if(typeof v.settings[k]!=='string'||!v.settings[k].trim())ctx.addIssue({code:'custom',message:`Completa el campo ${k}.`});}if(!/^\d{10,15}$/.test(v.settings.whatsapp||''))ctx.addIssue({code:'custom',message:'El número de WhatsApp debe incluir código de país, sin espacios.'});if(!/^#[a-fA-F0-9]{6}$/.test(v.settings.accent||''))ctx.addIssue({code:'custom',message:'El color debe tener formato hexadecimal.'});for(const k of ['logo','heroImage','storeImage'])if(!image.safeParse(v.settings[k]).success)ctx.addIssue({code:'custom',message:`Imagen no válida: ${k}.`});});
export async function readContent(){const row=await db().prepare('SELECT value, revision FROM content WHERE id = ?').bind('site').first<{value:string;revision:number}>();return row?{data:JSON.parse(row.value) as Content,revision:row.revision}:{data:initialContent,revision:0};}
export function hex(buffer:ArrayBuffer){return Array.from(new Uint8Array(buffer),b=>b.toString(16).padStart(2,'0')).join('')}
export async function digest(input:string){return hex(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(input)))}
export async function passwordHash(password:string,salt:string){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);return hex(await crypto.subtle.deriveBits({name:'PBKDF2',salt:new TextEncoder().encode(salt),iterations:100000,hash:'SHA-256'},key,256));}
export function equal(a:string,b:string){let diff=a.length^b.length;for(let i=0;i<Math.max(a.length,b.length);i++)diff|=(a.charCodeAt(i)||0)^(b.charCodeAt(i)||0);return diff===0;}
export type Admin={username:string;hash:string;salt:string;version:number;must_change:number};
export async function adminRecord(){let admin=await db().prepare('SELECT * FROM admins WHERE username = ?').bind('admin').first<Admin>();if(!admin&&runtime.ADMIN_INITIAL_HASH&&runtime.ADMIN_INITIAL_SALT){await db().prepare('INSERT OR IGNORE INTO admins (username, hash, salt, version, must_change) VALUES (?, ?, ?, 1, 1)').bind('admin',runtime.ADMIN_INITIAL_HASH,runtime.ADMIN_INITIAL_SALT).run();admin=await db().prepare('SELECT * FROM admins WHERE username = ?').bind('admin').first<Admin>();}return admin;}
function cookieToken(request:Request){return request.headers.get('cookie')?.split(';').map(x=>x.trim()).find(x=>x.startsWith('medicalshop_session='))?.slice('medicalshop_session='.length)||'';}
export async function authenticate(request:Request){const token=cookieToken(request);if(!/^[a-f0-9]{64}$/.test(token))return null;return db().prepare('SELECT a.username, a.must_change, a.version FROM sessions s JOIN admins a ON a.username = s.username AND a.version = s.version WHERE s.token = ? AND s.expires > ?').bind(await digest(token),Date.now()).first<{username:string;must_change:number;version:number}>();}
export async function removeSession(request:Request){const token=cookieToken(request);if(token)await db().prepare('DELETE FROM sessions WHERE token = ?').bind(await digest(token)).run();}
export function sessionCookie(request:Request,token:string,maxAge=28800){return `medicalshop_session=${token}; Path=/; HttpOnly; SameSite=Strict; Max-Age=${maxAge}${new URL(request.url).protocol==='https:'?'; Secure':''}`;}
export async function loginLimit(request:Request){const ip=request.headers.get('cf-connecting-ip')||'local';const now=Date.now();const key=await digest(`login:${ip}`);await db().prepare('INSERT INTO login_attempts (key, count, reset) VALUES (?, 1, ?) ON CONFLICT(key) DO UPDATE SET count = CASE WHEN reset < ? THEN 1 ELSE count + 1 END, reset = CASE WHEN reset < ? THEN excluded.reset ELSE reset END').bind(key,now+15*60*1000,now,now).run();const row=await db().prepare('SELECT count FROM login_attempts WHERE key = ?').bind(key).first<{count:number}>();return (row?.count||0)>10;}
