'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {ArrowUpRight,Search,SlidersHorizontal,X,MapPin,MessageCircle,HeartHandshake,Shirt,Menu,Plus,Check,LoaderCircle} from 'lucide-react';
import {Content,Product,whatsappUrl} from './data';
export function Visual({image,crop,alt,className=''}:{image:string;crop?:number[];alt:string;className?:string}){return <div className={`visual ${className}`}>{crop?<img alt={alt} loading="lazy" src={image} style={{width:`${(crop[4]||1024)/crop[2]*100}%`,maxWidth:'none',position:'absolute',left:`${-crop[0]/crop[2]*100}%`,top:`${-crop[1]/crop[3]*100}%`,height:`${(crop[5]||1536)/crop[3]*100}%`}}/>:<img src={image} alt={alt} loading="lazy"/>}</div>}
export default function Storefront({initial}:{initial:Content}){
const [data,setData]=useState(initial),[loading,setLoading]=useState(true),[error,setError]=useState(''),[category,setCategory]=useState('all'),[query,setQuery]=useState(''),[sort,setSort]=useState('featured'),[min,setMin]=useState(''),[max,setMax]=useState(''),[stock,setStock]=useState('all'),[filters,setFilters]=useState(false),[menu,setMenu]=useState(false),[selected,setSelected]=useState<Product|null>(null),[size,setSize]=useState(''),[color,setColor]=useState('');
const dialog=useRef<HTMLDialogElement>(null);const s=data.settings;const active=data.categories.find(c=>c.id===category);
useEffect(()=>{const ctrl=new AbortController();const timeout=setTimeout(()=>ctrl.abort(),12000);fetch('/api/content',{signal:ctrl.signal}).then(r=>{if(!r.ok)throw Error();return r.json() as Promise<Content>}).then(setData).catch(()=>setError('No se pudo actualizar el catálogo. Mostramos la selección inicial; confirma disponibilidad por WhatsApp.')).finally(()=>{setLoading(false);clearTimeout(timeout)});const u=new URL(location.href);setCategory(u.searchParams.get('categoria')||'all');setQuery(u.searchParams.get('buscar')||'');return()=>{clearTimeout(timeout);ctrl.abort()}},[]);
useEffect(()=>{if(selected){setSize('');setColor('');dialog.current?.showModal()}else dialog.current?.close()},[selected]);
function choose(id:string){setCategory(id);setMenu(false);const u=new URL(location.href);id==='all'?u.searchParams.delete('categoria'):u.searchParams.set('categoria',id);history.replaceState(null,'',u);}
const products=useMemo(()=>data.products.filter(p=>p.visible&&(category==='all'||p.category===category)&&`${p.name} ${p.description}`.toLocaleLowerCase('es').normalize('NFD').replace(/[\u0300-\u036f]/g,'').includes(query.toLocaleLowerCase('es').normalize('NFD').replace(/[\u0300-\u036f]/g,''))&&(!min||(p.price!==null&&p.price>=Number(min)))&&(!max||(p.price!==null&&p.price<=Number(max)))&&(stock==='all'||p.stock===stock)).sort((a,b)=>sort==='asc'?(a.price??Infinity)-(b.price??Infinity):sort==='desc'?(b.price??-1)-(a.price??-1):sort==='name'?a.name.localeCompare(b.name):Number(b.featured)-Number(a.featured)),[data,category,query,min,max,stock,sort]);
useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const ctrl=new AbortController();Promise.resolve(context.registerTool({name:'filter_catalog',description:'Filtra el catálogo visible por nombre o categoría.',inputSchema:{type:'object',properties:{query:{type:'string'},category:{type:'string'}},additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:any)=>{if(typeof input!=='object'||(input.query!==undefined&&typeof input.query!=='string')||(input.category!==undefined&&!['all',...data.categories.map(c=>c.id)].includes(input.category)))throw Error('Filtro inválido');setQuery(input.query||'');choose(input.category||'all');return {query:input.query||'',category:input.category||'all'};}},{signal:ctrl.signal})).catch(()=>{});return()=>ctrl.abort()},[data.categories]);
return <div style={{'--accent':s.accent} as React.CSSProperties}>
{loading&&<div className="loading-screen" role="status"><img src={s.logo} alt={s.brand}/><LoaderCircle className="spin"/><span>Preparando tu próxima jornada</span></div>}
<div className="announcement"><span>{s.announcement}</span><span>Jaén, Perú <MapPin size={13}/></span></div>
<header className="header wrap"><a href="/" className="brand" aria-label={s.brand}><img src={s.logo} alt={s.brand}/></a><nav className={menu?'nav open':'nav'}><a href="/catalogo" onClick={()=>setMenu(false)}>Catálogo</a><a href="/categorias" onClick={()=>setMenu(false)}>Categorías</a><a href="/nosotros" onClick={()=>setMenu(false)}>Nosotros</a><a href="/visitanos" onClick={()=>setMenu(false)}>Visítanos</a></nav><a className="button small outline header-contact" href={whatsappUrl(s.whatsapp)} target="_blank" rel="noreferrer"><MessageCircle size={17}/> Hablemos</a><button className="icon-button menu-toggle" aria-label="Abrir menú" aria-expanded={menu} onClick={()=>setMenu(!menu)}><Menu/></button></header>
<main><section className={`hero wrap ${active?'category-hero':''}`} key={category}><div className="hero-copy"><p className="eyebrow">{active?active.name:'MEDICALSHOP JAÉN'}</p><h1>{active?active.title:s.heroTitle}</h1><p className="hero-description">{active?active.description:s.heroDescription}</p><a href="#catalogo" className="button">{active?'Ver productos':s.heroButton}<ArrowUpRight size={20}/></a></div><div className="hero-picture">{active?<Visual image={active.image} crop={active.crop} alt={active.name}/>:<img src={s.heroImage} alt="Profesionales de la salud con uniformes azul marino y celeste" fetchPriority="high"/>}<div className="hero-caption"><span>Hecho para tu jornada.</span><span>Elegido por ti.</span></div></div></section>
<div className="service-strip wrap"><span><HeartHandshake/>{s.service1}</span><span><Shirt/>{s.service2}</span><span><MessageCircle/>{s.service3}</span></div>
<section id="categorias" className="categories-section wrap"><div className="section-heading"><h2>{s.categoriesTitle}</h2><button className="text-button" onClick={()=>{choose('all');document.getElementById('catalogo')?.scrollIntoView({behavior:'smooth'})}}>Ver todo <ArrowUpRight size={18}/></button></div><div className="category-list">{data.categories.map(c=><button key={c.id} className={`category-tile ${category===c.id?'active':''}`} onClick={()=>{choose(c.id);window.scrollTo({top:0,behavior:'smooth'})}}><Visual image={c.image} crop={c.crop} alt={c.name}/><span>{c.name}<ArrowUpRight size={17}/></span></button>)}</div></section>
<section id="catalogo" className="catalog wrap"><div className="section-heading"><div><p className="eyebrow">TU SELECCIÓN, EN UN SOLO LUGAR</p><h2>{active?active.name:s.catalogTitle}</h2></div><span className="count">{products.length} productos</span></div><div className="catalog-tools"><label className="search"><Search size={19}/><span className="sr-only">Buscar productos</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="¿Qué estás buscando?"/>{query&&<button aria-label="Borrar búsqueda" onClick={()=>setQuery('')}><X size={16}/></button>}</label><button className={`filter-button ${filters?'active':''}`} onClick={()=>setFilters(!filters)} aria-expanded={filters}><SlidersHorizontal size={17}/> Filtros</button><label className="sort"><span className="sr-only">Ordenar productos</span><select value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Destacados primero</option><option value="asc">Precio: menor a mayor</option><option value="desc">Precio: mayor a menor</option><option value="name">Nombre: A a Z</option></select></label></div>
<div className="category-tabs"><button className={category==='all'?'active':''} onClick={()=>choose('all')}>Todo el catálogo</button>{data.categories.map(c=><button className={category===c.id?'active':''} key={c.id} onClick={()=>choose(c.id)}>{c.name}</button>)}</div>
{filters&&<div className="filters"><label>Precio mínimo (S/)<input type="number" min="0" value={min} onChange={e=>setMin(e.target.value)} placeholder="Sin mínimo"/></label><label>Precio máximo (S/)<input type="number" min="0" value={max} onChange={e=>setMax(e.target.value)} placeholder="Sin máximo"/></label><label>Disponibilidad<select value={stock} onChange={e=>setStock(e.target.value)}><option value="all">Todas</option><option>Disponible</option><option>Consultar</option><option>Agotado</option></select></label><button className="text-button" onClick={()=>{setMin('');setMax('');setStock('all');setQuery('');choose('all')}}>Limpiar filtros <X size={16}/></button><small>Los productos sin precio publicado se excluyen al filtrar por precio.</small></div>}
{error&&<p className="notice" role="alert">{error}</p>}<div className="product-grid">{products.map(p=><article className="product" key={p.id}><button className="product-image" onClick={()=>setSelected(p)} aria-label={`Ver ${p.name}`}><Visual image={p.image} crop={p.crop} alt={p.name}/><span className="product-open"><Plus size={20}/></span></button><p className="product-category">{data.categories.find(c=>c.id===p.category)?.name}</p><button className="product-name" onClick={()=>setSelected(p)}>{p.name}</button><div className="product-bottom"><span>{p.price===null?'Precio a consultar':`S/ ${p.price.toFixed(2)}`}</span><a href={whatsappUrl(s.whatsapp,p.name)} target="_blank" rel="noreferrer" aria-label={`Consultar ${p.name} por WhatsApp`}><MessageCircle size={18}/><span>Consultar</span></a></div>{p.stock==='Agotado'&&<small>Agotado · Consulta alternativas</small>}</article>)}</div>{products.length===0&&<div className="empty"><Search size={32}/><h3>No encontramos productos con esos filtros.</h3><p>Prueba con otro nombre o amplía el rango de precio.</p><button className="button" onClick={()=>{setQuery('');setMin('');setMax('');setStock('all');choose('all')}}>Ver todos los productos</button></div>}<p className="catalog-note">{s.catalogNote}</p></section>
<section className="about wrap" id="nosotros"><div className="store-photo"><img src={s.storeImage} alt="Referencia del espacio de Medicalshop Jaén" loading="lazy"/></div><div className="about-copy"><p className="eyebrow">TU TIENDA MÉDICA EN JAÉN</p><h2>{s.aboutTitle}</h2><p>{s.aboutText}</p><a className="text-button" href="#contacto">Conoce dónde estamos <ArrowUpRight size={19}/></a></div></section>
<section className="contact wrap" id="contacto"><h2>{s.contactTitle}</h2><div className="contact-content"><p>{s.contactText}</p><div><MapPin size={24}/><div><strong>{s.address}</strong><p>{s.locationNote}</p><a className="text-button" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(s.address)}`} target="_blank" rel="noreferrer">Cómo llegar <ArrowUpRight size={16}/></a></div></div><a className="button" href={whatsappUrl(s.whatsapp)} target="_blank" rel="noreferrer"><MessageCircle size={18}/> Escríbenos por WhatsApp</a></div></section>
</main><footer className="footer wrap"><div><a className="brand" href="/"><img src={s.logo} alt={s.brand}/></a><p>{s.footerText}</p></div><div><span>© {new Date().getFullYear()} {s.brand}</span><a href="/admin">Administración <ArrowUpRight size={14}/></a></div></footer><a className="floating-whatsapp" href={whatsappUrl(s.whatsapp)} target="_blank" rel="noreferrer" aria-label="Escribir por WhatsApp"><MessageCircle size={27}/></a>
<dialog ref={dialog} className="product-dialog" onCancel={()=>setSelected(null)} onClick={e=>{if(e.target===dialog.current)setSelected(null)}}>{selected&&<><button className="close icon-button" onClick={()=>setSelected(null)} aria-label="Cerrar producto"><X/></button><Visual image={selected.image} crop={selected.crop} alt={selected.name}/><div className="product-detail"><p className="eyebrow">{data.categories.find(c=>c.id===selected.category)?.name}</p><h2>{selected.name}</h2><p>{selected.description}</p><strong className="detail-price">{selected.price===null?'Precio a consultar':`S/ ${selected.price.toFixed(2)}`}</strong><p className="stock">{selected.stock==='Disponible'?<Check size={16}/>:null}{selected.stock==='Consultar'?'Disponibilidad a confirmar':selected.stock}</p>{selected.sizes&&<label>Talla<select value={size} onChange={e=>setSize(e.target.value)}><option value="">Selecciona una talla</option>{selected.sizes.split(',').map(v=><option key={v}>{v.trim()}</option>)}</select></label>}{selected.colors&&<label>Color<select value={color} onChange={e=>setColor(e.target.value)}><option value="">Selecciona un color</option>{selected.colors.split(',').map(v=><option key={v}>{v.trim()}</option>)}</select></label>}<a className="button" href={whatsappUrl(s.whatsapp,selected.name,[size&&`Talla: ${size}`,color&&`Color: ${color}`].filter(Boolean).join('. '))} target="_blank" rel="noreferrer"><MessageCircle size={19}/> Consultar por WhatsApp</a><small>Confirma las características y disponibilidad con nuestro equipo.</small></div></>}</dialog>
</div>}
