'use client';
import {useEffect,useMemo,useState} from 'react';
import {ArrowLeft,ArrowRight,ArrowUpRight,MapPin,MessageCircle,Search,SlidersHorizontal,LoaderCircle} from 'lucide-react';
import {Content,Product,initialContent,whatsappUrl} from './data';
import {Visual} from './storefront';

type View='catalogo'|'categorias'|'nosotros'|'visitanos';
function Header({data}:{data:Content}){const s=data.settings;return <><div className="announcement"><span>{s.announcement}</span><span>Jaén, Perú <MapPin size={13}/></span></div><header className="header wrap"><a href="/" className="brand" aria-label={s.brand}><img src={s.logo} alt={s.brand}/></a><nav className="nav"><a href="/catalogo">Catálogo</a><a href="/categorias">Categorías</a><a href="/nosotros">Nosotros</a><a href="/visitanos">Visítanos</a></nav><a className="button small outline header-contact" href={whatsappUrl(s.whatsapp)} target="_blank" rel="noreferrer"><MessageCircle size={17}/> Hablemos</a></header></>}
function Footer({data}:{data:Content}){const s=data.settings;return <footer className="footer wrap"><div><a className="brand" href="/"><img src={s.logo} alt={s.brand}/></a><p>{s.footerText}</p></div><div><span>© {new Date().getFullYear()} {s.brand}</span><a href="/admin">Administración <ArrowUpRight size={14}/></a></div></footer>}
function Layout({data,children}:{data:Content;children:React.ReactNode}){return <div style={{'--accent':data.settings.accent} as React.CSSProperties}><Header data={data}/>{children}<Footer data={data}/><a className="floating-whatsapp" href={whatsappUrl(data.settings.whatsapp)} target="_blank" rel="noreferrer" aria-label="Escribir por WhatsApp"><MessageCircle size={27}/></a></div>}
function PageHero({kicker,title,description,image}:{kicker:string;title:string;description:string;image:string}){return <section className="subpage-hero wrap"><div><p className="eyebrow">{kicker}</p><h1>{title}</h1><p>{description}</p></div><img src={image} alt=""/></section>}
function Catalog({data}:{data:Content}){const s=data.settings;const [q,setQ]=useState(''),[cat,setCat]=useState('all'),[sort,setSort]=useState('featured'),[filters,setFilters]=useState(false),[min,setMin]=useState(''),[max,setMax]=useState('');const products=useMemo(()=>data.products.filter(p=>p.visible&&(cat==='all'||p.category===cat)&&`${p.name} ${p.description}`.toLocaleLowerCase('es').includes(q.toLocaleLowerCase('es'))&&(!min||(p.price!==null&&p.price>=+min))&&(!max||(p.price!==null&&p.price<=+max))).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):sort==='asc'?(a.price??Infinity)-(b.price??Infinity):sort==='desc'?(b.price??-1)-(a.price??-1):Number(b.featured)-Number(a.featured)),[data,q,cat,sort,min,max]);return <><PageHero kicker="CATÁLOGO MEDICALSHOP" title="Todo lo que necesitas para cuidar." description="Explora la selección de uniformes, equipos e insumos. Consulta cada producto directamente con nuestro equipo." image={s.heroImage}/><main className="catalog wrap subpage-content"><div className="catalog-tools"><label className="search"><Search size={19}/><span className="sr-only">Buscar productos</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="¿Qué estás buscando?"/></label><button className="filter-button" onClick={()=>setFilters(!filters)}><SlidersHorizontal size={17}/> Filtros</button><label className="sort"><span className="sr-only">Ordenar productos</span><select value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Destacados primero</option><option value="asc">Precio: menor a mayor</option><option value="desc">Precio: mayor a menor</option><option value="name">Nombre: A a Z</option></select></label></div><div className="category-tabs"><button className={cat==='all'?'active':''} onClick={()=>setCat('all')}>Todo el catálogo</button>{data.categories.map(c=><button className={cat===c.id?'active':''} key={c.id} onClick={()=>setCat(c.id)}>{c.name}</button>)}</div>{filters&&<div className="filters"><label>Precio mínimo (S/)<input type="number" value={min} onChange={e=>setMin(e.target.value)} placeholder="Sin mínimo"/></label><label>Precio máximo (S/)<input type="number" value={max} onChange={e=>setMax(e.target.value)} placeholder="Sin máximo"/></label><button className="text-button" onClick={()=>{setMin('');setMax('');setQ('');setCat('all')}}>Limpiar filtros</button></div>}<div className="product-grid">{products.map(p=><CatalogProduct key={p.id} product={p} data={data}/>)}</div>{!products.length&&<div className="empty"><h3>No encontramos productos con esos filtros.</h3><button className="button" onClick={()=>{setMin('');setMax('');setQ('');setCat('all')}}>Ver todos</button></div>}</main></>}
function CatalogProduct({product:p,data}:{product:Product;data:Content}){const cat=data.categories.find(c=>c.id===p.category);return <article className="product"><a className="product-image" href={whatsappUrl(data.settings.whatsapp,p.name)} target="_blank" rel="noreferrer"><Visual image={p.image} crop={p.crop} alt={p.name}/><span className="product-open"><ArrowUpRight size={18}/></span></a><p className="product-category">{cat?.name}</p><a className="product-name" href={whatsappUrl(data.settings.whatsapp,p.name)} target="_blank" rel="noreferrer">{p.name}</a><div className="product-bottom"><span>{p.price===null?'Precio a consultar':`S/ ${p.price.toFixed(2)}`}</span><a href={whatsappUrl(data.settings.whatsapp,p.name)} target="_blank" rel="noreferrer"><MessageCircle size={18}/><span>Consultar</span></a></div></article>}
function Categories({data}:{data:Content}){return <><PageHero kicker="ENCUENTRA TU CATEGORÍA" title="Una selección pensada para tu jornada." description="Elige una familia de productos y descubre opciones para profesionales, estudiantes y espacios de atención." image={data.settings.heroImage}/><main className="wrap subpage-content"><div className="category-page-grid">{data.categories.map(c=><a className="category-page-card" key={c.id} href={`/catalogo?categoria=${c.id}`}><Visual image={c.image} crop={c.crop} alt={c.name}/><div><p className="eyebrow">CATEGORÍA</p><h2>{c.name}</h2><p>{c.description}</p><span>Explorar categoría <ArrowRight size={17}/></span></div></a>)}</div></main></>}
function About({data}:{data:Content}){const s=data.settings;return <><PageHero kicker="MEDICALSHOP JAÉN" title={s.aboutTitle} description={s.aboutText} image={s.storeImage}/><main className="wrap subpage-content about-page"><section><p className="eyebrow">NUESTRA FORMA DE ACOMPAÑARTE</p><h2>Elegir bien también es parte de cuidar.</h2><p>Conocemos la rutina de quienes trabajan y estudian en salud. Por eso reunimos prendas cómodas, accesorios útiles y equipamiento para que encuentres todo en un mismo lugar.</p></section><section className="about-facts"><div><strong>01</strong><span>Atención cercana en tienda y por WhatsApp.</span></div><div><strong>02</strong><span>Variedad de colores, modelos y tallas.</span></div><div><strong>03</strong><span>Asesoría para elegir lo que realmente necesitas.</span></div></section><a className="button" href="/catalogo">Explorar el catálogo <ArrowUpRight size={18}/></a></main></>}
function Visit({data}:{data:Content}){const s=data.settings;return <><PageHero kicker="VISÍTANOS EN JAÉN" title={s.contactTitle} description={s.contactText} image={s.storeImage}/><main className="wrap subpage-content visit-page"><div className="visit-card"><MapPin size={28}/><p className="eyebrow">DÓNDE ENCONTRARNOS</p><h2>{s.address}</h2><p>{s.locationNote}</p><a className="text-button" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(s.address)}`} target="_blank" rel="noreferrer">Abrir ubicación en Maps <ArrowUpRight size={17}/></a></div><div className="visit-card blue"><MessageCircle size={28}/><p className="eyebrow">CONVERSEMOS</p><h2>¿Tienes una consulta sobre un producto?</h2><p>Escríbenos y te ayudamos con modelos, tallas, precios y disponibilidad.</p><a className="button" href={whatsappUrl(s.whatsapp)} target="_blank" rel="noreferrer">Escribir por WhatsApp <ArrowUpRight size={18}/></a></div></main></>}
export default function Subpage({view}:{view:View}){const [data,setData]=useState(initialContent);useEffect(()=>{fetch('/api/content').then(r=>r.ok?r.json():null).then(v=>v&&setData(v)).catch(()=>{})},[]);let page=view==='catalogo'?<Catalog data={data}/>:view==='categorias'?<Categories data={data}/>:view==='nosotros'?<About data={data}/>:<Visit data={data}/>;return <Layout data={data}>{page}</Layout>}
